title: "Show & Tell"
labels: ["showcase"]
body:
  - type: markdown
    attributes:
      value: |
        Built something cool with QuantumClaw? Show it off. Skills, setups, integrations, agent personalities, anything.
  - type: textarea
    attributes:
      label: What you built
      description: Tell us about it. Screenshots welcome.
    validations:
      required: true
