name: Bug Report
description: Something isn't working
title: "[Bug] "
labels: ["bug"]
body:
  - type: markdown
    attributes:
      value: |
        Thanks for reporting. Please fill in what you can — the more detail, the faster we can fix it.

  - type: textarea
    attributes:
      label: What happened?
      description: A clear description of the bug.
    validations:
      required: true

  - type: textarea
    attributes:
      label: What did you expect?
      description: What should have happened instead.
    validations:
      required: true

  - type: textarea
    attributes:
      label: Steps to reproduce
      description: How can we recreate this?
      placeholder: |
        1. Run `npx quantumclaw start`
        2. Send a message via Telegram
        3. See error in terminal
    validations:
      required: true

  - type: dropdown
    attributes:
      label: Platform
      options:
        - Linux (Ubuntu/Debian)
        - Linux (Fedora/RHEL)
        - Linux (Arch)
        - Linux (other)
        - macOS (Intel)
        - macOS (Apple Silicon)
        - Windows (WSL2)
        - Android (Termux)
        - Raspberry Pi
        - Docker
        - VPS
    validations:
      required: true

  - type: input
    attributes:
      label: Node.js version
      description: "Run: node --version"
      placeholder: "v22.x.x"
    validations:
      required: true

  - type: dropdown
    attributes:
      label: AI Provider
      options:
        - Anthropic (Claude)
        - OpenAI
        - Groq
        - OpenRouter
        - Google (Gemini)
        - Mistral
        - Together AI
        - xAI (Grok)
        - Ollama (local)
        - Other
    validations:
      required: false

  - type: textarea
    attributes:
      label: Diagnose output
      description: "Run `npx quantumclaw diagnose` and paste the output"
      render: text
    validations:
      required: false

  - type: textarea
    attributes:
      label: Error logs
      description: Any relevant error messages or logs
      render: text
    validations:
      required: false
